baseURL = 'https://deck.eddy.fun/'
languageCode = 'en-us'
title = 'Slide Deck'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
